version: "3.8"
services:
  web:
    build: ./apollo-nuxt
    ports:
      - "10.255.184.3:2001:2001"
      - "24678:24678"

  backend:
    build:
      context: ./ecommerce-go/server
    ports:
      - "10.255.184.3:2002:2002"
    environment:
      - TZ=Asia/Almaty

  vue-app:
    build:
      context: ./ecommerce-vue
      dockerfile: Dockerfile
    container_name: vue-app
    restart: always
    ports:
      - "10.255.184.3:2003:2003"

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - /certificates:/certs
