version: "3.8"
services:
  web:
    build: ./apollo-nuxt
    ports:
      - "89.46.33.148:2001:2001"
      - "24678:24678"

  backend:
    build:
      context: ./ecommerce-go/server
    ports:
      - "89.46.33.148:2002:2002"
    environment:
      - TZ=Asia/Almaty

  vue-app:
    build:
      context: ./ecommerce-vue
      dockerfile: Dockerfile
    container_name: vue-app
    restart: always
    ports:
      - "89.46.33.148:2003:2003"
